// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIsbk51wnbJElX3a3rf3iR495vmGOA6so',
    appId: '1:512206691328:web:b9fd9395d0083e38e58ce5',
    messagingSenderId: '512206691328',
    projectId: 'hondaku1',
    authDomain: 'hondaku1.firebaseapp.com',
    storageBucket: 'hondaku1.firebasestorage.app',
    measurementId: 'G-38EP74G7PY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA2rSmrtdvyO-ef4KURyQcz8DjeIA86fg',
    appId: '1:512206691328:android:0818e5d5060f5113e58ce5',
    messagingSenderId: '512206691328',
    projectId: 'hondaku1',
    storageBucket: 'hondaku1.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApWjxMzfm5E8ddF07NMHzYr9DVRy7CYs0',
    appId: '1:512206691328:ios:52f0f95592330a5ce58ce5',
    messagingSenderId: '512206691328',
    projectId: 'hondaku1',
    storageBucket: 'hondaku1.firebasestorage.app',
    androidClientId: '512206691328-5rvgtaj6l2coido732426sqdpv7vnqul.apps.googleusercontent.com',
    iosClientId: '512206691328-k0k0ftnj3c0mpvo1sekg8s1g4ltu8aa3.apps.googleusercontent.com',
    iosBundleId: 'com.example.hondaku',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApWjxMzfm5E8ddF07NMHzYr9DVRy7CYs0',
    appId: '1:512206691328:ios:52f0f95592330a5ce58ce5',
    messagingSenderId: '512206691328',
    projectId: 'hondaku1',
    storageBucket: 'hondaku1.firebasestorage.app',
    androidClientId: '512206691328-5rvgtaj6l2coido732426sqdpv7vnqul.apps.googleusercontent.com',
    iosClientId: '512206691328-k0k0ftnj3c0mpvo1sekg8s1g4ltu8aa3.apps.googleusercontent.com',
    iosBundleId: 'com.example.hondaku',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIsbk51wnbJElX3a3rf3iR495vmGOA6so',
    appId: '1:512206691328:web:86d51433ed9ad83de58ce5',
    messagingSenderId: '512206691328',
    projectId: 'hondaku1',
    authDomain: 'hondaku1.firebaseapp.com',
    storageBucket: 'hondaku1.firebasestorage.app',
    measurementId: 'G-99MTYS6970',
  );
}
