// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_WEB'] ?? 'AIzaSyCf5DbB3yUgDIlIC8fEo6kVrRur_B2ZuAo',
    appId: '1:675175751660:web:e9a047f8c4c82f08046ac9',
    messagingSenderId: '675175751660',
    projectId: 'hondaku-app',
    authDomain: 'hondaku-app.firebaseapp.com',
    storageBucket: 'hondaku-app.firebasestorage.app',
    measurementId: 'G-TSLEX6N0G8',
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_ANDROID'] ?? 'AIzaSyBr0xdIihN-uuHyJr_4nHFA-filDha0yYs',
    appId: '1:675175751660:android:64e988d81668171f046ac9',
    messagingSenderId: '675175751660',
    projectId: 'hondaku-app',
    storageBucket: 'hondaku-app.firebasestorage.app',
  );
  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_IOS'] ?? 'AIzaSyCYdeFHW3Nut7giz49gVDAd4egp78oF0oE',
    appId: '1:675175751660:ios:ca629ca72337d9c3046ac9',
    messagingSenderId: '675175751660',
    projectId: 'hondaku-app',
    storageBucket: 'hondaku-app.firebasestorage.app',
    iosClientId: '675175751660-704uhjme7lg5abria0q01uf415r0jedm.apps.googleusercontent.com',
    iosBundleId: 'com.example.hondaku',
  );
  static FirebaseOptions get macos => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_IOS'] ?? 'AIzaSyCYdeFHW3Nut7giz49gVDAd4egp78oF0oE',
    appId: '1:675175751660:ios:ca629ca72337d9c3046ac9',
    messagingSenderId: '675175751660',
    projectId: 'hondaku-app',
    storageBucket: 'hondaku-app.firebasestorage.app',
    iosClientId: '675175751660-704uhjme7lg5abria0q01uf415r0jedm.apps.googleusercontent.com',
    iosBundleId: 'com.example.hondaku',
  );

  static FirebaseOptions get windows => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_WEB'] ?? 'AIzaSyCf5DbB3yUgDIlIC8fEo6kVrRur_B2ZuAo',
    appId: '1:675175751660:web:34097c4cb6e299c1046ac9',
    messagingSenderId: '675175751660',
    projectId: 'hondaku-app',
    authDomain: 'hondaku-app.firebaseapp.com',
    storageBucket: 'hondaku-app.firebasestorage.app',
    measurementId: 'G-L4YWXWKC8M',
  );
}
